import React from "react";
import { Link } from "react-router-dom";
import { FileText, AlertCircle, Slash, Mail, CheckCircle, Scale } from "lucide-react";

const lastUpdated = "October 10, 2026";

const sections = [
  {
    id: "acceptance",
    icon: <CheckCircle className="h-5 w-5" />,
    title: "Acceptance of Terms",
    content: `By accessing or using LoopTalk ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use LoopTalk.

These Terms apply to all visitors, users, and others who access or use the Service. We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.

If you are using LoopTalk on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.`,
  },
  {
    id: "eligibility",
    icon: <CheckCircle className="h-5 w-5" />,
    title: "Eligibility",
    content: `To use LoopTalk, you must:
• Be at least 13 years of age
• Provide accurate and complete registration information
• Maintain the security of your account credentials
• Not have been previously suspended or removed from the Service

By creating an account, you confirm that you meet these eligibility requirements. Users between the ages of 13 and 18 must have parental or guardian consent.`,
  },
  {
    id: "your-account",
    icon: <FileText className="h-5 w-5" />,
    title: "Your Account",
    content: `You are responsible for:
• Maintaining the confidentiality of your account password
• All activities that occur under your account
• Notifying us immediately at support@looptalk.com if you suspect unauthorized access

You may not share your account with others or create multiple accounts to evade restrictions. LoopTalk reserves the right to suspend or terminate accounts that violate these Terms.`,
  },
  {
    id: "acceptable-use",
    icon: <CheckCircle className="h-5 w-5" />,
    title: "Acceptable Use",
    content: `You agree to use LoopTalk only for lawful purposes and in a manner that does not infringe the rights of others. Permitted uses include:
• Learning and practicing languages with other users
• Communicating via chat and video calls
• Using AI features to enhance your learning experience
• Building a personal knowledge base with the Second Brain

You agree not to use LoopTalk to spam other users, harvest contact information, or engage in any automated scraping.`,
  },
  {
    id: "prohibited",
    icon: <Slash className="h-5 w-5" />,
    title: "Prohibited Activities",
    content: `The following activities are strictly prohibited on LoopTalk:

• Harassment, bullying, or threatening other users
• Posting or sharing illegal, obscene, defamatory, or hateful content
• Impersonating any person or entity
• Distributing malware, viruses, or harmful code
• Attempting to gain unauthorized access to our systems
• Using the Service for commercial solicitation without permission
• Circumventing rate limits, security features, or access controls
• Engaging in any activity that disrupts or interferes with the Service

Violations may result in immediate account suspension or termination and may be reported to law enforcement.`,
  },
  {
    id: "content",
    icon: <FileText className="h-5 w-5" />,
    title: "User Content",
    content: `You retain ownership of the content you post on LoopTalk, including messages, profile information, and Second Brain entries.

By submitting content, you grant LoopTalk a limited, non-exclusive, royalty-free license to use, store, and display your content solely for the purpose of providing and improving the Service.

You are solely responsible for the content you post. LoopTalk does not endorse any user-generated content and is not liable for content submitted by users.

We reserve the right to remove any content that violates these Terms or our Community Guidelines without prior notice.`,
  },
  {
    id: "ai-features",
    icon: <FileText className="h-5 w-5" />,
    title: "AI Features",
    content: `LoopTalk offers AI-powered features including the AI Coach and Second Brain. By enabling these features:

• You grant us permission to process your conversation data to provide AI suggestions
• You understand that AI outputs are generated by machine learning models and may occasionally be inaccurate
• You agree not to rely solely on AI responses for medical, legal, or financial decisions
• You can withdraw consent for AI processing at any time in your account Settings

AI features are provided "as is" and we do not guarantee their accuracy or availability.`,
  },
  {
    id: "termination",
    icon: <AlertCircle className="h-5 w-5" />,
    title: "Termination",
    content: `You may stop using LoopTalk and delete your account at any time from your Profile Settings.

LoopTalk may suspend or terminate your access to the Service at any time, with or without cause, including if we believe:
• You have violated these Terms or our Community Guidelines
• Your use of the Service poses a security or legal risk
• Continued service is no longer commercially viable

Upon termination, your right to use the Service ceases immediately. Sections of these Terms that by their nature should survive termination will remain in effect.`,
  },
  {
    id: "disclaimers",
    icon: <AlertCircle className="h-5 w-5" />,
    title: "Disclaimers & Limitations",
    content: `The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. LoopTalk does not warrant that:
• The Service will be uninterrupted, error-free, or free of viruses
• The results obtained from using the Service will be accurate or reliable

To the maximum extent permitted by applicable law, LoopTalk shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.

Our total liability to you for any claim arising from these Terms or your use of the Service shall not exceed the amount you paid us in the 12 months prior to the claim, or $50 USD, whichever is greater.`,
  },
  {
    id: "governing-law",
    icon: <Scale className="h-5 w-5" />,
    title: "Governing Law",
    content: `These Terms are governed by and construed in accordance with the laws of India, without regard to its conflict of law principles. Any disputes arising from these Terms or your use of LoopTalk shall be subject to the exclusive jurisdiction of the courts located in India.

If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full force and effect.

These Terms, together with our Privacy Policy, constitute the entire agreement between you and LoopTalk regarding your use of the Service.`,
  },
];

export default function Terms() {
  return (
    <div className="min-h-screen bg-base-100 text-base-content">
      {/* Hero */}
      <section className="bg-gradient-to-br from-primary/10 via-base-100 to-secondary/10 py-20 px-6 text-center">
        <div className="mx-auto max-w-2xl">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary ring-1 ring-primary/20">
            <Scale className="h-4 w-4" />
            Terms of Service
          </div>
          <h1 className="mb-4 text-4xl font-extrabold tracking-tight lg:text-5xl">
            Terms of Service
          </h1>
          <p className="text-base-content/70 text-lg">
            Please read these terms carefully before using LoopTalk. By using
            our platform, you agree to be bound by these terms.
          </p>
          <p className="mt-4 text-sm text-base-content/50">Last Updated: {lastUpdated}</p>
        </div>
      </section>

      {/* Content */}
      <div className="mx-auto max-w-6xl px-6 py-16">
        <div className="flex flex-col gap-10 lg:flex-row">
          {/* Sidebar TOC */}
          <aside className="w-full shrink-0 lg:w-64">
            <div className="sticky top-24 rounded-2xl border border-base-300 bg-base-200 p-5">
              <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-base-content/50">
                Table of Contents
              </p>
              <nav className="space-y-1">
                {sections.map((s) => (
                  <a
                    key={s.id}
                    href={`#${s.id}`}
                    className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-base-content/70 transition hover:bg-base-100 hover:text-primary"
                  >
                    <span className="text-primary/60">{s.icon}</span>
                    {s.title}
                  </a>
                ))}
              </nav>
            </div>
          </aside>

          {/* Main */}
          <main className="flex-1 space-y-8">
            <div className="rounded-2xl border border-warning/30 bg-warning/5 p-5 text-sm text-base-content/70">
              <strong className="text-base-content">⚠️ Important:</strong> These are legally binding
              terms. By creating an account on LoopTalk, you agree to these
              Terms of Service. Please read them carefully.
            </div>

            {sections.map((section) => (
              <div
                key={section.id}
                id={section.id}
                className="scroll-mt-24 rounded-2xl border border-base-300 bg-base-200 p-7"
              >
                <div className="mb-4 flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
                    {section.icon}
                  </div>
                  <h2 className="text-xl font-bold">{section.title}</h2>
                </div>
                <div className="whitespace-pre-line text-sm leading-relaxed text-base-content/70">
                  {section.content}
                </div>
              </div>
            ))}

            {/* Contact */}
            <div className="rounded-2xl border border-base-300 bg-base-200 p-7">
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
                  <Mail className="h-5 w-5" />
                </div>
                <h2 className="text-xl font-bold">Questions About These Terms?</h2>
              </div>
              <p className="mb-4 text-sm leading-relaxed text-base-content/70">
                If you have any questions about these Terms of Service, please
                contact us:
              </p>
              <p className="text-sm text-base-content/80">
                📧{" "}
                <a
                  href="mailto:legal@looptalk.com"
                  className="font-medium text-primary underline underline-offset-2"
                >
                  legal@looptalk.com
                </a>
              </p>
              <p className="mt-1 text-sm text-base-content/60">
                We aim to respond to all legal inquiries within 5 business days.
              </p>
            </div>

            <div className="flex flex-wrap gap-3">
              <Link to="/privacy" className="btn btn-outline btn-sm rounded-full">
                View Privacy Policy
              </Link>
              <Link to="/about" className="btn btn-ghost btn-sm rounded-full">
                About LoopTalk
              </Link>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}
